### ISSUE TITLE
USER STORY: View List Of Food Recipe Posts

### ISSUE THREAD

**Issue by Jem212Mac** [Jem212Mac/the-gabby-gourmand#11]
As a **site user** I can **view a list of all food recipe posts** so that I can choose a food recipe post I want to view

### Acceptance Criteria:

- Acceptance Criteria 1: If a user clicks on the food recipes page, a list of all food recipe posts is displayed.
- Acceptance Criteria 2: If there is more than one food recipe post available, multiple posts are listed.
- Acceptance Criteria 3: The user sees a list of all available food recipe posts, with pagination.

### Tasks:

- [x] Add path to food recipes in urls.py.
- [x] Add FoodList class to views.py with queryset to pick out only food recipes.
- [x] Create food.html template.
- [x] Add link to food.html template in base.html.
