### ISSUE TITLE
USER STORY: View List Of Cocktail Recipe Posts

### ISSUE THREAD

**Issue by Jem212Mac** [Jem212Mac/the-gabby-gourmand#12]
As a **site user** I can **view a list of all cocktail recipe posts** so that I can choose a cocktail recipe post I want to view

### Acceptance Criteria:

- Acceptance Criteria 1: If a user clicks on the cocktail recipes page, a list of all cocktail recipe posts is displayed.
- Acceptance Criteria 2: If there is more than one cocktail recipe post available, multiple posts are listed.
- Acceptance Criteria 3: The user sees a list of all available cocktail recipe posts, with pagination.

### Tasks:

- [x] Add path to cocktail recipes in urls.py.
- [x] Add CocktailList class to views.py with queryset to pick out only cocktail recipes.
- [x] Create cocktail.html template.
- [x] Add link to cocktail.html template in base.html.
