### ISSUE TITLE
USER STORY: View List Of Restaurant Review Posts

### ISSUE THREAD

**Issue by Jem212Mac** [Jem212Mac/the-gabby-gourmand#13]
As a **site user** I can **view a list of all restaurant review posts** so that I can choose a restaurant review post I want to view

### Acceptance Criteria:

- Acceptance Criteria 1: If a user clicks on the home page, a list of all restaurant review posts is displayed.
- Acceptance Criteria 2: If there is more than one restaurant review post available, multiple posts are listed.
- Acceptance Criteria 3: The user sees a list of all available restaurant review posts, with pagination.

### Tasks:
- [x] Create initial unstyled homepage from review_list.html.
- [x] Create a base.html file and index.html file for the list of restaurant reviews (should appear on the home page).
- [x] Create some custom styling (to be completed later) with style.css file.
- [x] Install whitenoise and run collectstatic to ready the static files for production.
- [x] Deploy to heroku.
