### ISSUE TITLE
Task: Setup Django Project, App, Database, Superuser & Environment Variables

### ISSUE THREAD

**Issue by Jem212Mac** [Jem212Mac/the-gabby-gourmand#18]
### Tasks:

- [x] Install Django.
- [x] Add Django package to requirements.txt.
- [x] Create new project 'gabbygourmand'.
- [x] Create new blog app.
- [x] Add new blog app to settings.py.
- [x] Update views.py.
- [x] Add new path in urls.py.
- [x] Run the server to check.
- [x] Deploy the project to heroku.
- [x] Create and connect to database.
- [x] Create a superuser.
- [x] Deploy to heroku.
- [x] Create secret key.
- [x] Deploy to heroku.
