### ISSUE TITLE
USER STORY: View A Post

### ISSUE THREAD

**Issue by Jem212Mac** [Jem212Mac/the-gabby-gourmand#2]
As a **site user** I can **click on a post** so that **I can read the full text**

### Acceptance Criteria:

- Acceptance Criteria 1: When a post is clicked on, a detailed view of the post is displayed.

### Tasks:

- [x] Add path to review_detail in blog/urls.py.
- [x] Update index.html to add link to review_detail view.
- [x] Add review_detail function to blog/views.py.
- [x] Add default image to static/images directory.
- [x] Create review_html template.
- [x] Add path to food_detail in blog/urls.py.
- [x] Update food.html to add link to food_detail view.
- [x] Add food_detail function to blog/views.py.
- [x] Create food.detail_html template.
- [x] Add path to cocktail_detail in blog/urls.py.
- [x] Update cocktail.html to add link to cocktail_detail view.
- [x] Add cocktail_detail function to blog/views.py.
- [x] Create cocktail.detail_html template.
- [x] collectstatic.
- [x] Deploy to heroku and check ability to view restaurant review, food recipe, and cocktail recipe posts.
