### ISSUE TITLE
Task: Manual Testing

### ISSUE THREAD

**Issue by Jem212Mac** [Jem212Mac/the-gabby-gourmand#23]
### Tasks:

- [x] Create a manual test script to test site.
- [x] Execute manual test script.
- [x] Analyse and fix bugs.
- [x] Perform code validator testing (PEP8 etc).
