### ISSUE TITLE
Task: Automated Testing

### ISSUE THREAD

**Issue by Jem212Mac** [Jem212Mac/the-gabby-gourmand#24]
### Tasks:

- [x] Create and execute unit tests for the blog forms.py file.
- [x] Create and execute unit tests for the blog views.py file.
- [x] Create and execute unit tests for the blog urls.py file.
- [x] Create and execute unit tests for the about forms.py file.
- [x] Create amd execute unit tests for the about views.py file.
