### ISSUE TITLE
USER STORY: Account Registration

### ISSUE THREAD

**Issue by Jem212Mac** [Jem212Mac/the-gabby-gourmand#4]
As a **site user** I can **register for an account** so that **I can comment on posts**

### Acceptance Criteria:

- Acceptance Criteria 1: A user can register an account with a username and password.
- Acceptance Criteria 2: Once registered, a user can log in.
- Acceptance Criteria 3: When logged in, a user can comment on a post.

### Tasks:
- [x] Add and setup Django AllAuth to the project.
- [x] Add login, signup and logout url's and links to the base.html file.
- [x] Copy the allauth template files to the project templates directory.
- [x] Add base.html and bootstrap styles to the login.html, logout.html and signup.html files.
- [x] Add a personalise login message when user logged in.
- [x] Add message to let user know if logged out.
- [x] Deploy to heroku.
- [x] Check user can login, logout, or signup and check correct options displayed in navbar dependent on login status.
