### ISSUE TITLE
USER STORY: Comment On A Post

### ISSUE THREAD

**Issue by Jem212Mac** [Jem212Mac/the-gabby-gourmand#5]
As a **site user** I can **leave comments on a post** so that **I can engage in the conversation**

### Acceptance Criteria:

- Acceptance Criteria 1: Given a user is logged in, they can comment on a post.
- Acceptance Criteria 2: A user's comment will only be visible to themselves (not publicly visible) until the comment is approved by a site admin.
- Acceptance Criteria 3: More than one comment will result in a conversation thread.

### Tasks:

- [x] Install django crispy forms and crispy bootstrap and add to installed apps in project.
- [x] Add a new forms.py.
- [x] Add comment forms to food_detail and cocktail_detail views and html siles.
- [x] Add confirmation message.
