### ISSUE TITLE
USER STORY: Manage Posts

### ISSUE THREAD

**Issue by Jem212Mac** [Jem212Mac/the-gabby-gourmand#8]
As a **site admin** I can **create, read, update and delete posts** so that I can **manage my blog content**

### Acceptance Criteria:

- Acceptance Criteria 1: Given a logged in site admin, they can create a blog post.
- Acceptance Criteria 2: Given a logged in site admin, they can read a blog post.
- Acceptance Criteria 3: Given a logged in site admin, they can update a blog post.
- Acceptance Criteria 4: Given a logged in site admin, they can delete a blog post.

### Tasks:
- [x] Create a Review model and add it to the database.
- [x] Create a Recipe model and add it to the database.
- [x] Create a Comment model and add it to the database.
- [x] As a site admin, add some Users, some Restaurant Reviews, some Recipes and some Comments to the database.
- [x] As a site admin, check all CRUD functionality is possible for all Restaurant Reviews, Recipes, and Comments (regardless of the original author) via Django Admin.
- [x] Add django summernote to assist with editing of posts.
